.PHONY: install test sandbox clean update-requirements

install:
	pip install -r requirements.testing.txt
	./setup.py develop

test:
	./runtests.py

sandbox: install
	pip install -r requirements.sandbox.txt
	-rm sandbox/db.sqlite
	sandbox/manage.py migrate
	sandbox/manage.py loaddata sandbox/fixtures/users.json

clean:
	find . -type f -name "*.pyc" -delete
	rm -rf htmlcov *.egg-info *.pdf dist

update-requirements:
	pip-compile requirements.sandbox.in || echo "\n\nPlease install pip-compile: pip install git+https://github.com/blueyed/pip-tools.git@fixes-for-pip\n\n"
	sed -i '1s;^;# This file is auto-generated by make update-requirements.\n\n;' requirements.sandbox.txt
	pip-compile requirements.testing.in
	sed -i '1s;^;# This file is auto-generated by make update-requirements.\n\n;' requirements.testing.txt
