# Generated by Django 3.0.11 on 2020-11-09 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oscar_accounts', '0003_alter_ip_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transfer',
            name='username',
            field=models.CharField(max_length=150),
        ),
    ]
